/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastrarEmpresaRouteImport } from './routes/cadastrar.empresa'
import { Route as CadastrarCaminhoneiroRouteImport } from './routes/cadastrar.caminhoneiro'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppMotoristaRouteImport } from './routes/_app/motorista'
import { Route as AppMetricasRouteImport } from './routes/_app/metricas'
import { Route as AppMensagensRapidasRouteImport } from './routes/_app/mensagens-rapidas'
import { Route as AppEmpresaRouteImport } from './routes/_app/empresa'
import { Route as AppDisponibilidadeRouteImport } from './routes/_app/disponibilidade'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppColaboradorRouteImport } from './routes/_app/colaborador'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDisponibilidadeIndexRouteImport } from './routes/_app/disponibilidade.index'
import { Route as AppDisponibilidadeMotoristasRouteImport } from './routes/_app/disponibilidade.motoristas'
import { Route as AppDisponibilidadeEmpresasRouteImport } from './routes/_app/disponibilidade.empresas'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarEmpresaRoute = CadastrarEmpresaRouteImport.update({
  id: '/cadastrar/empresa',
  path: '/cadastrar/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarCaminhoneiroRoute = CadastrarCaminhoneiroRouteImport.update({
  id: '/cadastrar/caminhoneiro',
  path: '/cadastrar/caminhoneiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMotoristaRoute = AppMotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMetricasRoute = AppMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMensagensRapidasRoute = AppMensagensRapidasRouteImport.update({
  id: '/mensagens-rapidas',
  path: '/mensagens-rapidas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDisponibilidadeRoute = AppDisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppColaboradorRoute = AppColaboradorRouteImport.update({
  id: '/colaborador',
  path: '/colaborador',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDisponibilidadeIndexRoute = AppDisponibilidadeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDisponibilidadeRoute,
} as any)
const AppDisponibilidadeMotoristasRoute =
  AppDisponibilidadeMotoristasRouteImport.update({
    id: '/motoristas',
    path: '/motoristas',
    getParentRoute: () => AppDisponibilidadeRoute,
  } as any)
const AppDisponibilidadeEmpresasRoute =
  AppDisponibilidadeEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AppDisponibilidadeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/colaborador': typeof AppColaboradorRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/disponibilidade': typeof AppDisponibilidadeRouteWithChildren
  '/empresa': typeof AppEmpresaRoute
  '/mensagens-rapidas': typeof AppMensagensRapidasRoute
  '/metricas': typeof AppMetricasRoute
  '/motorista': typeof AppMotoristaRoute
  '/perfil': typeof AppPerfilRoute
  '/usuarios': typeof AppUsuariosRoute
  '/cadastrar/caminhoneiro': typeof CadastrarCaminhoneiroRoute
  '/cadastrar/empresa': typeof CadastrarEmpresaRoute
  '/disponibilidade/empresas': typeof AppDisponibilidadeEmpresasRoute
  '/disponibilidade/motoristas': typeof AppDisponibilidadeMotoristasRoute
  '/disponibilidade/': typeof AppDisponibilidadeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/colaborador': typeof AppColaboradorRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/empresa': typeof AppEmpresaRoute
  '/mensagens-rapidas': typeof AppMensagensRapidasRoute
  '/metricas': typeof AppMetricasRoute
  '/motorista': typeof AppMotoristaRoute
  '/perfil': typeof AppPerfilRoute
  '/usuarios': typeof AppUsuariosRoute
  '/cadastrar/caminhoneiro': typeof CadastrarCaminhoneiroRoute
  '/cadastrar/empresa': typeof CadastrarEmpresaRoute
  '/disponibilidade/empresas': typeof AppDisponibilidadeEmpresasRoute
  '/disponibilidade/motoristas': typeof AppDisponibilidadeMotoristasRoute
  '/disponibilidade': typeof AppDisponibilidadeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/colaborador': typeof AppColaboradorRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/disponibilidade': typeof AppDisponibilidadeRouteWithChildren
  '/_app/empresa': typeof AppEmpresaRoute
  '/_app/mensagens-rapidas': typeof AppMensagensRapidasRoute
  '/_app/metricas': typeof AppMetricasRoute
  '/_app/motorista': typeof AppMotoristaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/cadastrar/caminhoneiro': typeof CadastrarCaminhoneiroRoute
  '/cadastrar/empresa': typeof CadastrarEmpresaRoute
  '/_app/disponibilidade/empresas': typeof AppDisponibilidadeEmpresasRoute
  '/_app/disponibilidade/motoristas': typeof AppDisponibilidadeMotoristasRoute
  '/_app/disponibilidade/': typeof AppDisponibilidadeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/colaborador'
    | '/configuracoes'
    | '/disponibilidade'
    | '/empresa'
    | '/mensagens-rapidas'
    | '/metricas'
    | '/motorista'
    | '/perfil'
    | '/usuarios'
    | '/cadastrar/caminhoneiro'
    | '/cadastrar/empresa'
    | '/disponibilidade/empresas'
    | '/disponibilidade/motoristas'
    | '/disponibilidade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/colaborador'
    | '/configuracoes'
    | '/empresa'
    | '/mensagens-rapidas'
    | '/metricas'
    | '/motorista'
    | '/perfil'
    | '/usuarios'
    | '/cadastrar/caminhoneiro'
    | '/cadastrar/empresa'
    | '/disponibilidade/empresas'
    | '/disponibilidade/motoristas'
    | '/disponibilidade'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/colaborador'
    | '/_app/configuracoes'
    | '/_app/disponibilidade'
    | '/_app/empresa'
    | '/_app/mensagens-rapidas'
    | '/_app/metricas'
    | '/_app/motorista'
    | '/_app/perfil'
    | '/_app/usuarios'
    | '/cadastrar/caminhoneiro'
    | '/cadastrar/empresa'
    | '/_app/disponibilidade/empresas'
    | '/_app/disponibilidade/motoristas'
    | '/_app/disponibilidade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CadastrarCaminhoneiroRoute: typeof CadastrarCaminhoneiroRoute
  CadastrarEmpresaRoute: typeof CadastrarEmpresaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar/empresa': {
      id: '/cadastrar/empresa'
      path: '/cadastrar/empresa'
      fullPath: '/cadastrar/empresa'
      preLoaderRoute: typeof CadastrarEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar/caminhoneiro': {
      id: '/cadastrar/caminhoneiro'
      path: '/cadastrar/caminhoneiro'
      fullPath: '/cadastrar/caminhoneiro'
      preLoaderRoute: typeof CadastrarCaminhoneiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/motorista': {
      id: '/_app/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof AppMotoristaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/metricas': {
      id: '/_app/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AppMetricasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mensagens-rapidas': {
      id: '/_app/mensagens-rapidas'
      path: '/mensagens-rapidas'
      fullPath: '/mensagens-rapidas'
      preLoaderRoute: typeof AppMensagensRapidasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/empresa': {
      id: '/_app/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/disponibilidade': {
      id: '/_app/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/disponibilidade'
      preLoaderRoute: typeof AppDisponibilidadeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/colaborador': {
      id: '/_app/colaborador'
      path: '/colaborador'
      fullPath: '/colaborador'
      preLoaderRoute: typeof AppColaboradorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/disponibilidade/': {
      id: '/_app/disponibilidade/'
      path: '/'
      fullPath: '/disponibilidade/'
      preLoaderRoute: typeof AppDisponibilidadeIndexRouteImport
      parentRoute: typeof AppDisponibilidadeRoute
    }
    '/_app/disponibilidade/motoristas': {
      id: '/_app/disponibilidade/motoristas'
      path: '/motoristas'
      fullPath: '/disponibilidade/motoristas'
      preLoaderRoute: typeof AppDisponibilidadeMotoristasRouteImport
      parentRoute: typeof AppDisponibilidadeRoute
    }
    '/_app/disponibilidade/empresas': {
      id: '/_app/disponibilidade/empresas'
      path: '/empresas'
      fullPath: '/disponibilidade/empresas'
      preLoaderRoute: typeof AppDisponibilidadeEmpresasRouteImport
      parentRoute: typeof AppDisponibilidadeRoute
    }
  }
}

interface AppDisponibilidadeRouteChildren {
  AppDisponibilidadeEmpresasRoute: typeof AppDisponibilidadeEmpresasRoute
  AppDisponibilidadeMotoristasRoute: typeof AppDisponibilidadeMotoristasRoute
  AppDisponibilidadeIndexRoute: typeof AppDisponibilidadeIndexRoute
}

const AppDisponibilidadeRouteChildren: AppDisponibilidadeRouteChildren = {
  AppDisponibilidadeEmpresasRoute: AppDisponibilidadeEmpresasRoute,
  AppDisponibilidadeMotoristasRoute: AppDisponibilidadeMotoristasRoute,
  AppDisponibilidadeIndexRoute: AppDisponibilidadeIndexRoute,
}

const AppDisponibilidadeRouteWithChildren =
  AppDisponibilidadeRoute._addFileChildren(AppDisponibilidadeRouteChildren)

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppColaboradorRoute: typeof AppColaboradorRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDisponibilidadeRoute: typeof AppDisponibilidadeRouteWithChildren
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppMensagensRapidasRoute: typeof AppMensagensRapidasRoute
  AppMetricasRoute: typeof AppMetricasRoute
  AppMotoristaRoute: typeof AppMotoristaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppColaboradorRoute: AppColaboradorRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDisponibilidadeRoute: AppDisponibilidadeRouteWithChildren,
  AppEmpresaRoute: AppEmpresaRoute,
  AppMensagensRapidasRoute: AppMensagensRapidasRoute,
  AppMetricasRoute: AppMetricasRoute,
  AppMotoristaRoute: AppMotoristaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CadastrarCaminhoneiroRoute: CadastrarCaminhoneiroRoute,
  CadastrarEmpresaRoute: CadastrarEmpresaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
