/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DisponibilidadeRouteImport } from './routes/disponibilidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DisponRouteImport } from './routes/_dispon'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisponibilidadeIndexRouteImport } from './routes/disponibilidade.index'
import { Route as DisponibilidadeMotoristasRouteImport } from './routes/disponibilidade.motoristas'
import { Route as DisponibilidadeEmpresasRouteImport } from './routes/disponibilidade.empresas'
import { Route as CadastrarEmpresaRouteImport } from './routes/cadastrar.empresa'
import { Route as CadastrarCaminhoneiroRouteImport } from './routes/cadastrar.caminhoneiro'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppMotoristaRouteImport } from './routes/_app/motorista'
import { Route as AppMetricasRouteImport } from './routes/_app/metricas'
import { Route as AppMensagensRapidasRouteImport } from './routes/_app/mensagens-rapidas'
import { Route as AppEmpresaRouteImport } from './routes/_app/empresa'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppColaboradorRouteImport } from './routes/_app/colaborador'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as DisponMotoristaDisponivelRouteImport } from './routes/_dispon.motorista.disponivel'
import { Route as DisponFretesDisponivelRouteImport } from './routes/_dispon.fretes.disponivel'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisponibilidadeRoute = DisponibilidadeRouteImport.update({
  id: '/disponibilidade',
  path: '/disponibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DisponRoute = DisponRouteImport.update({
  id: '/_dispon',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisponibilidadeIndexRoute = DisponibilidadeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisponibilidadeRoute,
} as any)
const DisponibilidadeMotoristasRoute =
  DisponibilidadeMotoristasRouteImport.update({
    id: '/motoristas',
    path: '/motoristas',
    getParentRoute: () => DisponibilidadeRoute,
  } as any)
const DisponibilidadeEmpresasRoute = DisponibilidadeEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => DisponibilidadeRoute,
} as any)
const CadastrarEmpresaRoute = CadastrarEmpresaRouteImport.update({
  id: '/cadastrar/empresa',
  path: '/cadastrar/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarCaminhoneiroRoute = CadastrarCaminhoneiroRouteImport.update({
  id: '/cadastrar/caminhoneiro',
  path: '/cadastrar/caminhoneiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMotoristaRoute = AppMotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMetricasRoute = AppMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMensagensRapidasRoute = AppMensagensRapidasRouteImport.update({
  id: '/mensagens-rapidas',
  path: '/mensagens-rapidas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppColaboradorRoute = AppColaboradorRouteImport.update({
  id: '/colaborador',
  path: '/colaborador',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const DisponMotoristaDisponivelRoute =
  DisponMotoristaDisponivelRouteImport.update({
    id: '/motorista/disponivel',
    path: '/motorista/disponivel',
    getParentRoute: () => DisponRoute,
  } as any)
const DisponFretesDisponivelRoute = DisponFretesDisponivelRouteImport.update({
  id: '/fretes/disponivel',
  path: '/fretes/disponivel',
  getParentRoute: () => DisponRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/disponibilidade': typeof DisponibilidadeRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/colaborador': typeof AppColaboradorRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/empresa': typeof AppEmpresaRoute
  '/mensagens-rapidas': typeof AppMensagensRapidasRoute
  '/metricas': typeof AppMetricasRoute
  '/motorista': typeof AppMotoristaRoute
  '/perfil': typeof AppPerfilRoute
  '/usuarios': typeof AppUsuariosRoute
  '/cadastrar/caminhoneiro': typeof CadastrarCaminhoneiroRoute
  '/cadastrar/empresa': typeof CadastrarEmpresaRoute
  '/disponibilidade/empresas': typeof DisponibilidadeEmpresasRoute
  '/disponibilidade/motoristas': typeof DisponibilidadeMotoristasRoute
  '/disponibilidade/': typeof DisponibilidadeIndexRoute
  '/fretes/disponivel': typeof DisponFretesDisponivelRoute
  '/motorista/disponivel': typeof DisponMotoristaDisponivelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/colaborador': typeof AppColaboradorRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/empresa': typeof AppEmpresaRoute
  '/mensagens-rapidas': typeof AppMensagensRapidasRoute
  '/metricas': typeof AppMetricasRoute
  '/motorista': typeof AppMotoristaRoute
  '/perfil': typeof AppPerfilRoute
  '/usuarios': typeof AppUsuariosRoute
  '/cadastrar/caminhoneiro': typeof CadastrarCaminhoneiroRoute
  '/cadastrar/empresa': typeof CadastrarEmpresaRoute
  '/disponibilidade/empresas': typeof DisponibilidadeEmpresasRoute
  '/disponibilidade/motoristas': typeof DisponibilidadeMotoristasRoute
  '/disponibilidade': typeof DisponibilidadeIndexRoute
  '/fretes/disponivel': typeof DisponFretesDisponivelRoute
  '/motorista/disponivel': typeof DisponMotoristaDisponivelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_dispon': typeof DisponRouteWithChildren
  '/auth': typeof AuthRoute
  '/disponibilidade': typeof DisponibilidadeRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/colaborador': typeof AppColaboradorRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/empresa': typeof AppEmpresaRoute
  '/_app/mensagens-rapidas': typeof AppMensagensRapidasRoute
  '/_app/metricas': typeof AppMetricasRoute
  '/_app/motorista': typeof AppMotoristaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/cadastrar/caminhoneiro': typeof CadastrarCaminhoneiroRoute
  '/cadastrar/empresa': typeof CadastrarEmpresaRoute
  '/disponibilidade/empresas': typeof DisponibilidadeEmpresasRoute
  '/disponibilidade/motoristas': typeof DisponibilidadeMotoristasRoute
  '/disponibilidade/': typeof DisponibilidadeIndexRoute
  '/_dispon/fretes/disponivel': typeof DisponFretesDisponivelRoute
  '/_dispon/motorista/disponivel': typeof DisponMotoristaDisponivelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/disponibilidade'
    | '/reset-password'
    | '/admin'
    | '/colaborador'
    | '/configuracoes'
    | '/empresa'
    | '/mensagens-rapidas'
    | '/metricas'
    | '/motorista'
    | '/perfil'
    | '/usuarios'
    | '/cadastrar/caminhoneiro'
    | '/cadastrar/empresa'
    | '/disponibilidade/empresas'
    | '/disponibilidade/motoristas'
    | '/disponibilidade/'
    | '/fretes/disponivel'
    | '/motorista/disponivel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/colaborador'
    | '/configuracoes'
    | '/empresa'
    | '/mensagens-rapidas'
    | '/metricas'
    | '/motorista'
    | '/perfil'
    | '/usuarios'
    | '/cadastrar/caminhoneiro'
    | '/cadastrar/empresa'
    | '/disponibilidade/empresas'
    | '/disponibilidade/motoristas'
    | '/disponibilidade'
    | '/fretes/disponivel'
    | '/motorista/disponivel'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_dispon'
    | '/auth'
    | '/disponibilidade'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/colaborador'
    | '/_app/configuracoes'
    | '/_app/empresa'
    | '/_app/mensagens-rapidas'
    | '/_app/metricas'
    | '/_app/motorista'
    | '/_app/perfil'
    | '/_app/usuarios'
    | '/cadastrar/caminhoneiro'
    | '/cadastrar/empresa'
    | '/disponibilidade/empresas'
    | '/disponibilidade/motoristas'
    | '/disponibilidade/'
    | '/_dispon/fretes/disponivel'
    | '/_dispon/motorista/disponivel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DisponRoute: typeof DisponRouteWithChildren
  AuthRoute: typeof AuthRoute
  DisponibilidadeRoute: typeof DisponibilidadeRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  CadastrarCaminhoneiroRoute: typeof CadastrarCaminhoneiroRoute
  CadastrarEmpresaRoute: typeof CadastrarEmpresaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disponibilidade': {
      id: '/disponibilidade'
      path: '/disponibilidade'
      fullPath: '/disponibilidade'
      preLoaderRoute: typeof DisponibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dispon': {
      id: '/_dispon'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DisponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disponibilidade/': {
      id: '/disponibilidade/'
      path: '/'
      fullPath: '/disponibilidade/'
      preLoaderRoute: typeof DisponibilidadeIndexRouteImport
      parentRoute: typeof DisponibilidadeRoute
    }
    '/disponibilidade/motoristas': {
      id: '/disponibilidade/motoristas'
      path: '/motoristas'
      fullPath: '/disponibilidade/motoristas'
      preLoaderRoute: typeof DisponibilidadeMotoristasRouteImport
      parentRoute: typeof DisponibilidadeRoute
    }
    '/disponibilidade/empresas': {
      id: '/disponibilidade/empresas'
      path: '/empresas'
      fullPath: '/disponibilidade/empresas'
      preLoaderRoute: typeof DisponibilidadeEmpresasRouteImport
      parentRoute: typeof DisponibilidadeRoute
    }
    '/cadastrar/empresa': {
      id: '/cadastrar/empresa'
      path: '/cadastrar/empresa'
      fullPath: '/cadastrar/empresa'
      preLoaderRoute: typeof CadastrarEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar/caminhoneiro': {
      id: '/cadastrar/caminhoneiro'
      path: '/cadastrar/caminhoneiro'
      fullPath: '/cadastrar/caminhoneiro'
      preLoaderRoute: typeof CadastrarCaminhoneiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/motorista': {
      id: '/_app/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof AppMotoristaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/metricas': {
      id: '/_app/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AppMetricasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/mensagens-rapidas': {
      id: '/_app/mensagens-rapidas'
      path: '/mensagens-rapidas'
      fullPath: '/mensagens-rapidas'
      preLoaderRoute: typeof AppMensagensRapidasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/empresa': {
      id: '/_app/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/colaborador': {
      id: '/_app/colaborador'
      path: '/colaborador'
      fullPath: '/colaborador'
      preLoaderRoute: typeof AppColaboradorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_dispon/motorista/disponivel': {
      id: '/_dispon/motorista/disponivel'
      path: '/motorista/disponivel'
      fullPath: '/motorista/disponivel'
      preLoaderRoute: typeof DisponMotoristaDisponivelRouteImport
      parentRoute: typeof DisponRoute
    }
    '/_dispon/fretes/disponivel': {
      id: '/_dispon/fretes/disponivel'
      path: '/fretes/disponivel'
      fullPath: '/fretes/disponivel'
      preLoaderRoute: typeof DisponFretesDisponivelRouteImport
      parentRoute: typeof DisponRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppColaboradorRoute: typeof AppColaboradorRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppMensagensRapidasRoute: typeof AppMensagensRapidasRoute
  AppMetricasRoute: typeof AppMetricasRoute
  AppMotoristaRoute: typeof AppMotoristaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppColaboradorRoute: AppColaboradorRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppMensagensRapidasRoute: AppMensagensRapidasRoute,
  AppMetricasRoute: AppMetricasRoute,
  AppMotoristaRoute: AppMotoristaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DisponRouteChildren {
  DisponFretesDisponivelRoute: typeof DisponFretesDisponivelRoute
  DisponMotoristaDisponivelRoute: typeof DisponMotoristaDisponivelRoute
}

const DisponRouteChildren: DisponRouteChildren = {
  DisponFretesDisponivelRoute: DisponFretesDisponivelRoute,
  DisponMotoristaDisponivelRoute: DisponMotoristaDisponivelRoute,
}

const DisponRouteWithChildren =
  DisponRoute._addFileChildren(DisponRouteChildren)

interface DisponibilidadeRouteChildren {
  DisponibilidadeEmpresasRoute: typeof DisponibilidadeEmpresasRoute
  DisponibilidadeMotoristasRoute: typeof DisponibilidadeMotoristasRoute
  DisponibilidadeIndexRoute: typeof DisponibilidadeIndexRoute
}

const DisponibilidadeRouteChildren: DisponibilidadeRouteChildren = {
  DisponibilidadeEmpresasRoute: DisponibilidadeEmpresasRoute,
  DisponibilidadeMotoristasRoute: DisponibilidadeMotoristasRoute,
  DisponibilidadeIndexRoute: DisponibilidadeIndexRoute,
}

const DisponibilidadeRouteWithChildren = DisponibilidadeRoute._addFileChildren(
  DisponibilidadeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  DisponRoute: DisponRouteWithChildren,
  AuthRoute: AuthRoute,
  DisponibilidadeRoute: DisponibilidadeRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  CadastrarCaminhoneiroRoute: CadastrarCaminhoneiroRoute,
  CadastrarEmpresaRoute: CadastrarEmpresaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
